{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOSAbehwCrEOrBuaBma4EE/",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Ibrahim-Abduljabar/Vetly-AI/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "6zKv5BXqh2Bj",
        "outputId": "f120e0ed-b6ca-4847-d3d1-d38c87c7b902"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting groq\n",
            "  Downloading groq-1.5.0-py3-none-any.whl.metadata (16 kB)\n",
            "Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.13.0)\n",
            "Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)\n",
            "Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)\n",
            "Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)\n",
            "Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.18)\n",
            "Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.5.20)\n",
            "Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)\n",
            "Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)\n",
            "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)\n",
            "Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)\n",
            "Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)\n",
            "Downloading groq-1.5.0-py3-none-any.whl (143 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m143.7/143.7 kB\u001b[0m \u001b[31m3.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: groq\n",
            "Successfully installed groq-1.5.0\n",
            "Collecting pypdf\n",
            "  Downloading pypdf-6.14.2-py3-none-any.whl.metadata (7.2 kB)\n",
            "Downloading pypdf-6.14.2-py3-none-any.whl (349 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m349.5/349.5 kB\u001b[0m \u001b[31m7.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pypdf\n",
            "Successfully installed pypdf-6.14.2\n",
            "Collecting python-docx\n",
            "  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)\n",
            "Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)\n",
            "Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.15.0)\n",
            "Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m253.0/253.0 kB\u001b[0m \u001b[31m5.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: python-docx\n",
            "Successfully installed python-docx-1.2.0\n",
            "Collecting fpdf2\n",
            "  Downloading fpdf2-2.8.7-py3-none-any.whl.metadata (81 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m81.0/81.0 kB\u001b[0m \u001b[31m3.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from fpdf2) (0.7.1)\n",
            "Requirement already satisfied: Pillow!=9.2.*,>=8.3.2 in /usr/local/lib/python3.12/dist-packages (from fpdf2) (11.3.0)\n",
            "Requirement already satisfied: fonttools>=4.34.0 in /usr/local/lib/python3.12/dist-packages (from fpdf2) (4.63.0)\n",
            "Downloading fpdf2-2.8.7-py3-none-any.whl (327 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m327.1/327.1 kB\u001b[0m \u001b[31m13.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: fpdf2\n",
            "Successfully installed fpdf2-2.8.7\n",
            "Collecting streamlit\n",
            "  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.1)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)\n",
            "Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)\n",
            "Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)\n",
            "Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)\n",
            "Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)\n",
            "Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)\n",
            "Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)\n",
            "Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)\n",
            "Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)\n",
            "Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)\n",
            "Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.2/9.2 MB\u001b[0m \u001b[31m19.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m11.3/11.3 MB\u001b[0m \u001b[31m78.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.2 streamlit-1.58.0\n"
          ]
        }
      ],
      "source": [
        "!pip install groq\n",
        "!pip install pypdf\n",
        "!pip install python-docx\n",
        "!pip install fpdf2\n",
        "!pip install streamlit"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "# تأكد من تثبيت المكتبة عبر: pip install groq\n",
        "from groq import Groq\n",
        "\n",
        "# 1. إعداد هوية الموقع والواجهة الفخمة لـ \"ولد أعمال\"\n",
        "st.set_page_config(page_title=\"Vetly AI\", page_icon=\"🎯\", layout=\"wide\")\n",
        "st.title(\"🎯 Vetly AI\")\n",
        "st.subheader(\"منظومة فرز وتوليد الأسئلة الفخاخ لكشف خبرة المرشحين ومنع الخداع\")\n",
        "\n",
        "# 2. استدعاء العميل باستخدام المتغير السري الخاص بك مباشرة (مخفي تماماً وصارم)\n",
        "# تأكد أن المتغير API_e معرف مسبقاً في بيئة عملك أو سيرفر Streamlit Secrets\n",
        "if 'API_e' in globals() or 'API_e' in locals():\n",
        "    client = Groq(api_key=API_e)\n",
        "else:\n",
        "    # احتياطياً لسيرفر Streamlit Cloud في الـ Production\n",
        "    try:\n",
        "        client = Groq(api_key=st.secrets[\"API_e\"])\n",
        "    except:\n",
        "        st.error(\"خطأ تكتيكي: المتغير السري API_e غير معرف في بيئة العمل!\")\n",
        "        st.stop()\n",
        "\n",
        "# 3. نظام جمع وحفظ الإيميلات (العملة الأساسية لجمع الـ 5000 إيميل)\n",
        "def save_lead_email(email):\n",
        "    if email and \"@\" in email:\n",
        "        with open(\"vetly_leads.txt\", \"a\", encoding=\"utf-8\") as f:\n",
        "            f.write(email + \"\\n\")\n",
        "        return True\n",
        "    return False\n",
        "\n",
        "# 4. لوحة التحكم الجانبية لمدراء الـ HR (لوضع متطلبات الوظيفة والمعايير)\n",
        "st.sidebar.header(\"🛠️ معايير فرز المقابلة\")\n",
        "job_description = st.sidebar.text_area(\"وصف متطلبات الوظيفة المستهدفة (Job Description):\",\n",
        "                                       placeholder=\"أدخل المهام والخبرات المطلوبة للوظيفة هنا...\")\n",
        "\n",
        "num_questions = st.sidebar.slider(\"عدد الأسئلة الفخاخ لكل مرشح:\", min_value=1, max_value=10, value=3)\n",
        "difficulty_level = st.sidebar.selectbox(\"مستوى صعوبة الفخاخ الفنية:\",\n",
        "                                         [\"سهل ومتدرج\", \"متوسط لاختبار الفهم\", \"صعب جداً وفخاخ تقنية عميقة\"])\n",
        "\n",
        "# 5. إدارة خانات الـ CVs الديناميكية (إضافة مرشحين متعددين بضغط زر)\n",
        "if \"cv_count\" not in st.session_state:\n",
        "    st.session_state.cv_count = 1  # نبدأ بمرشح واحد تلقائياً\n",
        "\n",
        "st.write(\"### 👥 السير الذاتية للمرشحين\")\n",
        "\n",
        "# مصفوفة لتخزين بيانات المرشحين المدخلة ديناميكياً\n",
        "candidates_data = []\n",
        "\n",
        "# الـ Loop الحركي لتوليد الخانات بناءً على ضغط المدراء لزر الإضافة\n",
        "for i in range(st.session_state.cv_count):\n",
        "    col1, col2 = st.columns([1, 4])\n",
        "    with col1:\n",
        "        c_name = st.text_input(f\"اسم المرشح #{i+1}\", value=f\"مرشح {i+1}\", key=f\"name_{i}\")\n",
        "    with col2:\n",
        "        c_cv = st.text_area(f\"نص السيرة الذاتية أو أهم مهارات المرشح #{i+1}\",\n",
        "                            placeholder=\"انسخ نص الـ CV أو الخبرات هنا...\", key=f\"cv_{i}\")\n",
        "    candidates_data.append({\"name\": c_name, \"cv\": c_cv})\n",
        "    st.divider()\n",
        "\n",
        "# زر إضافة خانة مرشح جديدة ديناميكياً دون مسح البيانات السابقة\n",
        "if st.button(\"➕ إضافة مرشح آخر للمقابلة المتقاطعة\"):\n",
        "    st.session_state.cv_count += 1\n",
        "    st.rerun()\n",
        "\n",
        "# 6. معالجة وتوليد الأسئلة الفخاخ عبر الـ API بدرجة حرارة 0.1 الصارمة لقتل الهلوسة\n",
        "if st.button(\"🔥 هندسة دليل الأسئلة الفخاخ فوراً\"):\n",
        "    if not job_description:\n",
        "        st.warning(\"الرجاء إدخال وصف الوظيفة أولاً في اللوحة الجانبية.\")\n",
        "    else:\n",
        "        st.write(\"### 🎯 دليل الأسئلة المخفية الجاهز للمدير:\")\n",
        "\n",
        "        system_instruction = \"\"\"\n",
        "        أنت مستشار توظيف تقني فذ ومسؤول فرز فني عسكري في كبرى الشركات. مهمتك قراءة السيرة الذاتية ومقارنتها بالوظيفة، واستخراج أسئلة بمثابة فخاخ تقنية دقيقة وعميقة لكشف الخبرة الحقيقية ومنع الخداع تماماً.\n",
        "        يجب أن تقدم الإجابة النموذجية البشرية المحترفة والمختصرة جداً التي يجب أن يسمعها المدير ليعرف إذا كان المرشح نصاباً أم خبيراً في نفس اللحظة.\n",
        "        \"\"\"\n",
        "\n",
        "        # معالجة كل مرشح في خانته بشكل منفصل ونظيف تماماً كمصفوفة\n",
        "        for person in candidates_data:\n",
        "            if person[\"cv\"]: # نتحقق أن الخانة ليست فارغة\n",
        "                with st.spinner(f\"جاري فحص الـ CV وهندسة الفخاخ لـ {person['name']}...\"):\n",
        "\n",
        "                    user_instruction = f\"\"\"\n",
        "                    قم بتوليد عدد ({num_questions}) أسئلة فخاخ بمستوى صعوبة ({difficulty_level}).\n",
        "\n",
        "                    المرشح: {person['name']}\n",
        "                    السيرة الذاتية: {person['cv']}\n",
        "                    الوظيفة المستهدفة: {job_description}\n",
        "\n",
        "                    التنسيق الصارم للمخرجات:\n",
        "                    👤 المرشح: [اسم المرشح]\n",
        "                    ❓ السؤال الفخ [الرقم]: [نص السؤال الفني الصعب والمباغت]\n",
        "                    💡 الإجابة النموذجية المتوقعة: [الجواب القصير الحاسم والعميق]\n",
        "                    \"\"\"\n",
        "\n",
        "                    # الاستدعاء المباشر بدرجة حرارة 0.1 الصارمة والمنيعة ضد الهلوسة\n",
        "                    chat_completion = client.chat.completions.create(\n",
        "                        model=\"llama3-70b-8192\",\n",
        "                        messages=[\n",
        "                            {\"role\": \"system\", \"content\": system_instruction},\n",
        "                            {\"role\": \"user\", \"content\": user_instruction}\n",
        "                        ],\n",
        "                        temperature=0.1\n",
        "                    )\n",
        "\n",
        "                    # عرض المخرجات فورا على شاشة واجهة الـ HR\n",
        "                    st.info(chat_completion.choices.message.content)\n",
        "\n",
        "        # 7. قفل الميزات التسويقي لجمع الإيميلات قبل التحميل\n",
        "        st.success(\"تم توليد الأسئلة بنجاح!\")\n",
        "        st.write(\"#### 🔒 فتح ميزة تحميل 'دليل المدير التنفيذي للمقابلات' (PDF)\")\n",
        "        lead_email = st.text_input(\"أدخل بريدك الإلكتروني التجاري لفك قفل تحميل ملف الـ PDF الجاهز للاجتماع:\")\n",
        "\n",
        "        if st.button(\"تحميل وثيقة المقابلة الرسمية\"):\n",
        "            if save_lead_email(lead_email):\n",
        "                st.success(\"تم تسجيل إيميلك بنجاح في قاعدة بيانات Vetly AI! جاري إعداد وتصدير ملف الـ PDF الفخم...\")\n",
        "                # هنا يوضع لاحقاً منطق توليد ملف الـ PDF بناءً على المخرجات\n",
        "            else:\n",
        "                st.error(\"الرجاء إدخال بريد إلكتروني حقيقي وصحيح لفك القفل.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Qf8MQUkajzq6",
        "outputId": "4f77beff-8f59-4596-ff7e-1f58add21086"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2026-06-26 06:29:44.020 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.029 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.314 \n",
            "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
            "  command:\n",
            "\n",
            "    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]\n",
            "2026-06-26 06:29:44.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.331 Session state does not function when running a script without `streamlit run`\n",
            "2026-06-26 06:29:44.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.336 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.337 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.338 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.338 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.343 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.344 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.344 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.346 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.348 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.350 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.351 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.361 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.366 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.372 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.375 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-06-26 06:29:44.375 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ]
    }
  ]
}